### ISSUE TITLE
Theme Option Improvement 1

### ISSUE THREAD

**Issue by KienTrong** [FameThemes/wp-coupon#16]
1. Settings->Header: Header background

2. Settings -> Footer: Custom your footer style : Doesn't work yet.

3. Please check again if Settings -> Custom Codes, Custom CSS is already works.

**Comment by shrimp2t** [comment]
Maybe we need to:
- Remove custom codes section settings
- Remove custom css 
Because the settings above don't allow by themeforest or wp org
