### ISSUE TITLE
Coupon thumbnail issue

### ISSUE THREAD

**Issue by KienTrong** [FameThemes/wp-coupon#37]
http://cl.ly/0u1r183R0O1I

**Comment by shrimp2t** [comment]
Can you explain more details about this bug ? the feature of the first coupon is empty but it still showing the feature of second coupon ?

**Comment by KienTrong** [comment]
The first coupon has no featured image, however it still show. Simple as that

**Comment by shrimp2t** [comment]
Still not found this bug maybe i'll fix latter.

**Comment by KienTrong** [comment]
Recreate: Apply coupon for multiple store and back to just one store.
Later.
